<?php
header('Content-Type: application/json');
require_once __DIR__ . '/../../backend/config.php';
require_once __DIR__ . '/../../backend/lib/ReportService.php';
require_once __DIR__ . '/../../backend/lib/GoogleDriveService.php';
require_once __DIR__ . '/../../backend/lib/Auth.php';
require_once __DIR__ . '/../../backend/lib/Permissions.php';

$method = $_SERVER['REQUEST_METHOD'];

if ($method !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'method_not_allowed']);
    exit;
}

try {
    $user = Auth::currentUser();
    if (!$user) {
        http_response_code(401);
        echo json_encode(['error' => 'unauthorized']);
        exit;
    }
    Permissions::allow('reports');

    $payload = json_decode(file_get_contents('php://input'), true) ?? [];
    $format = $payload['format'] ?? 'excel';
    $days = max(1, (int)($payload['days'] ?? 30));

    if (!in_array($format, ['excel', 'pdf', 'sql'])) {
        http_response_code(400);
        echo json_encode(['error' => 'invalid_format', 'message' => 'Format must be "excel", "pdf", or "sql"']);
        exit;
    }

    $tmpPath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('bbms_report_', true);

    if ($format === 'sql') {
        $filename = 'BBMS_Backup_' . date('Y-m-d_H-i-s') . '.sql';
        $mimeType = 'application/sql';
        $tmpPath .= '_' . basename($filename);
        generateSqlDump($tmpPath);
    } else {
        $data = [
            'donor_blood_groups' => ReportService::donorBloodGroups(),
            'daily_collections' => ReportService::dailyCollections($days),
            'screening_results' => ReportService::screeningResults($days),
            'inventory_snapshot' => ReportService::inventorySnapshot(),
            'issuance_daily' => ReportService::issuanceDaily($days),
            'generated_at' => date('Y-m-d H:i:s'),
            'generated_by' => $user['name'],
        ];

        // Generate file content
        if ($format === 'pdf') {
            $content = generatePdfContent($data, $days);
            $filename = 'BBMS_Report_' . date('Y-m-d_H-i-s') . '.pdf';
            $mimeType = 'application/pdf';
        } else {
            $content = generateExcelContent($data, $days);
            $filename = 'BBMS_Report_' . date('Y-m-d_H-i-s') . '.xls';
            $mimeType = 'application/vnd.ms-excel';
        }

        // Save report temporarily and upload through uploadReport helper.
        $tmpPath .= '_' . basename($filename);
        file_put_contents($tmpPath, $content);
    }

    $fileInfo = GoogleDriveService::uploadReport($tmpPath, $filename);
    @unlink($tmpPath);

    // Persist link in database for auditing/history
    $logDays = $format === 'sql' ? 0 : $days;
    ReportService::saveDriveExportLink($user['id'], $fileInfo['name'], $fileInfo['id'], $fileInfo['url'], $mimeType, $logDays);

    http_response_code(201);
    echo json_encode([
        'success' => true,
        'data' => $fileInfo,
        'message' => $format === 'sql'
            ? 'Database backup uploaded successfully to Google Drive'
            : 'Report uploaded successfully to Google Drive'
    ]);

} catch (InvalidArgumentException $e) {
    http_response_code(400);
    error_log('[drive-export] invalid argument: ' . $e->getMessage());
    echo json_encode(['error' => 'invalid_argument', 'message' => $e->getMessage()]);
} catch (RuntimeException $e) {
    http_response_code(500);
    error_log('[drive-export] drive_error: ' . $e->getMessage());
    echo json_encode(['error' => 'drive_error', 'message' => $e->getMessage()]);
} catch (Exception $e) {
    http_response_code(500);
    error_log('[drive-export] unexpected_error: ' . $e->getMessage());
    echo json_encode(['error' => 'drive_error', 'message' => 'Unexpected error: ' . $e->getMessage()]);
}

function generatePdfContent(array $data, int $days): string
{
    $lines = [];
    $lines[] = 'Blood Bank Management System - Report';
    $lines[] = 'Generated at: ' . $data['generated_at'];
    $lines[] = 'Generated by: ' . $data['generated_by'];
    $lines[] = 'Range: Last ' . $days . ' days';
    $lines[] = '';
    $lines[] = 'Donors by Blood Group';
    foreach ($data['donor_blood_groups'] as $row) {
        $lines[] = $row['blood_group'] . ' : ' . $row['total'];
    }
    $lines[] = '';
    $lines[] = 'Daily Collections';
    foreach ($data['daily_collections'] as $row) {
        $lines[] = $row['day'] . ' : ' . $row['total'];
    }
    $lines[] = '';
    $lines[] = 'Daily Issuance';
    foreach ($data['issuance_daily'] as $row) {
        $lines[] = $row['day'] . ' : ' . $row['total'];
    }
    $lines[] = '';
    $lines[] = 'Screening Results';
    foreach ($data['screening_results'] as $row) {
        $lines[] = $row['result_status'] . ' : ' . $row['total'];
    }
    $lines[] = '';
    $lines[] = 'Inventory Snapshot';
    foreach ($data['inventory_snapshot'] as $row) {
        $lines[] = $row['blood_group'] . ' - ' . $row['status'] . ' : ' . $row['total'];
    }

    $content = "BT\n/F1 12 Tf\n1 0 0 1 50 800 Tm\n14 TL\n";
    foreach ($lines as $line) {
        $safe = str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $line);
        $content .= '(' . $safe . ") Tj\n0 -14 Td\n";
    }
    $content .= "ET\n";

    $objects = [];
    $objects[] = "<< /Type /Catalog /Pages 2 0 R >>";
    $objects[] = "<< /Type /Pages /Kids [3 0 R] /Count 1 >>";
    $objects[] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>";
    $objects[] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
    $objects[] = "<< /Length " . strlen($content) . " >>\nstream\n" . $content . "endstream";

    $pdf = "%PDF-1.4\n";
    $offsets = [0];
    foreach ($objects as $i => $obj) {
        $offsets[] = strlen($pdf);
        $pdf .= ($i + 1) . " 0 obj\n" . $obj . "\nendobj\n";
    }
    $xrefPos = strlen($pdf);
    $pdf .= "xref\n0 " . (count($objects) + 1) . "\n";
    $pdf .= "0000000000 65535 f \n";
    for ($i = 1; $i <= count($objects); $i++) {
        $pdf .= str_pad((string)$offsets[$i], 10, '0', STR_PAD_LEFT) . " 00000 n \n";
    }
    $pdf .= "trailer\n<< /Size " . (count($objects) + 1) . " /Root 1 0 R >>\nstartxref\n" . $xrefPos . "\n%%EOF";

    return $pdf;
}

function generateExcelContent(array $data, int $days): string
{
    $html = "<table border=\"1\">";
    $html .= "<tr><th colspan=\"2\">Blood Bank Management System - Report</th></tr>";
    $html .= "<tr><td>Generated at</td><td>" . htmlspecialchars($data['generated_at']) . "</td></tr>";
    $html .= "<tr><td>Generated by</td><td>" . htmlspecialchars($data['generated_by']) . "</td></tr>";
    $html .= "<tr><td>Range</td><td>Last " . (int)$days . " days</td></tr>";
    $html .= "</table><br/>";

    $html .= "<table border=\"1\">";
    $html .= "<tr><th colspan=\"2\">Donors by Blood Group</th></tr>";
    foreach ($data['donor_blood_groups'] as $row) {
        $html .= "<tr><td>" . htmlspecialchars($row['blood_group']) . "</td><td>" . (int)$row['total'] . "</td></tr>";
    }
    $html .= "</table><br/>";

    $html .= "<table border=\"1\">";
    $html .= "<tr><th colspan=\"2\">Daily Collections</th></tr>";
    foreach ($data['daily_collections'] as $row) {
        $html .= "<tr><td>" . htmlspecialchars($row['day']) . "</td><td>" . (int)$row['total'] . "</td></tr>";
    }
    $html .= "</table><br/>";

    $html .= "<table border=\"1\">";
    $html .= "<tr><th colspan=\"2\">Daily Issuance</th></tr>";
    foreach ($data['issuance_daily'] as $row) {
        $html .= "<tr><td>" . htmlspecialchars($row['day']) . "</td><td>" . (int)$row['total'] . "</td></tr>";
    }
    $html .= "</table><br/>";

    $html .= "<table border=\"1\">";
    $html .= "<tr><th colspan=\"2\">Screening Results</th></tr>";
    foreach ($data['screening_results'] as $row) {
        $html .= "<tr><td>" . htmlspecialchars($row['result_status']) . "</td><td>" . (int)$row['total'] . "</td></tr>";
    }
    $html .= "</table><br/>";

    $html .= "<table border=\"1\">";
    $html .= "<tr><th colspan=\"3\">Inventory Snapshot</th></tr>";
    $html .= "<tr><th>Blood Group</th><th>Status</th><th>Total</th></tr>";
    foreach ($data['inventory_snapshot'] as $row) {
        $html .= "<tr><td>" . htmlspecialchars($row['blood_group']) . "</td><td>" . htmlspecialchars($row['status']) . "</td><td>" . (int)$row['total'] . "</td></tr>";
    }
    $html .= "</table>";

    return $html;
}

function generateSqlDump(string $filePath): void
{
    $dumpPath = BACKUP_MYSQLDUMP_PATH ?: 'mysqldump';
    $command = [
        $dumpPath,
        '--host=' . DB_HOST,
        '--user=' . DB_USER,
        '--default-character-set=utf8mb4',
        '--single-transaction',
        '--routines',
        '--events',
        '--triggers',
        '--databases',
        DB_NAME,
    ];

    if (DB_PASS !== '') {
        $command[] = '--password=' . DB_PASS;
    }

    $descriptorSpec = [
        0 => ['pipe', 'r'],
        1 => ['file', $filePath, 'w'],
        2 => ['pipe', 'w'],
    ];

    $process = proc_open($command, $descriptorSpec, $pipes);
    if (!is_resource($process)) {
        throw new RuntimeException('Unable to start mysqldump process.');
    }

    fclose($pipes[0]);
    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[2]);

    $exitCode = proc_close($process);
    if ($exitCode !== 0) {
        throw new RuntimeException('mysqldump failed: ' . trim($stderr));
    }

    if (!is_file($filePath) || filesize($filePath) === 0) {
        throw new RuntimeException('mysqldump did not produce a valid SQL file.');
    }
}
